name: WoodCurrency
main: eu.sidzej.wc.WoodCurrency
author: _CJ_ aka SiDzej
version: 1.0 - beta
depend: [Vault]
commands:
  wc:
    description: Main command for this plugin... it provide you help if you type it.
    aliases: [woodcurrency,wood]
    usage: /<command> help
permissions:
  woodcurrency.*:
    description: Gives access to all WoodCurrency commands
    default: false
    children:
      woodcurrency.moderator: true
      woodcurrency.player: true
      woodcurrency.disable: true
      
  woodcurrency.disable:
    description: Allow to switch off this plugin immediately.
    default: false
  
  woodcurrency.moderator:
    description: Usefull for server moderator - almost all commands access
    default: false
    children:
      woodcurrency.player: true
      woodcurrency.createshop: true
      woodcurrency.destroyshop: true
      woodcurrency.ban: true
      woodcurrency.unban: true
      woodcurrency.resettier: true
      woodcurrency.resetday: true
      woodcurrency.info.others: true
      woodcurrency.example: true
      
  woodcurrency.player:
    description: Standart commnads and action for players
    default: true
    children:
      woodcurrency.sell: true
      woodcurrency.buy: true
      woodcurrency.info: true
      woodcurrency.help: true
      woodcurrency.top: true
      
    
  woodcurrency.createshop:
    description: Allow player to place shop sign
    default: false
  woodcurrency.destroyshop:
    description: Allow player to destroy shop sign
    default: false
  woodcurrency.ban: 
    default: false
  woodcurrency.unban: 
    default: false
  woodcurrency.resettier: 
    default: false
  woodcurrency.resetday: 
    default: false
  woodcurrency.example:
    description: example how to setup shop
    default: false
    
    
  woodcurrency.buy:
    description: Allow buying things at shop
    default: true
  woodcurrency.sell:
    description: Allow selling things at shop
    default: true
    
  woodcurrency.info: 
    default: true
  woodcurrency.info.others: 
    default: false
  woodcurrency.help: 
    default: true
  woodcurrency.top: 
    default: true
  